### ISSUE TITLE
schema issue

### ISSUE THREAD

**Issue by iandelible** [team-megatron/chess-app#32]
https://github.com/team-megatron/chess-app/blob/db32f9a4b2ed33a8bcb89dbe569e2e153361b4ae/db/schema.rb

See lines 31-48 on the schema.rb

```ruby
create_table "identities", force: true do |t|
    t.integer  "user_id"
    t.string   "provider"
    t.string   "accesstoken"
    t.string   "refreshtoken"
    t.string   "uid"
    t.string   "name"
    t.string   "email"
    t.string   "nickname"
    t.string   "image"
    t.string   "phone"
    t.string   "urls"
    t.datetime "created_at"
    t.datetime "updated_at"
end

add_index "identities", ["user_id"], name: "index_identities_on_user_id", using: :btree
```

@dmk1991, I think those lines were added by accident because there is no corresponding migration file.

**Comment by chuong** [comment]
@iandelible I was puzzled by those lines in schema.rb too, and the ones starting with 

> create_table "users", force: true do |t|

These were reintroduced by `rake db:migrate` during my last PR, but I couldn't get rid of them. Now I find out that I have to stop rails sever and remove my schema.rb file before running 
```
$ rake db:reset
$ rake db:migrate
```
to create a clean file.

**Comment by iandelible** [comment]
@chuong Good point. I think the users was my fault, when I first did devise, I used "users" instead of "players" but forgot to clean up the file before pushing it.

**Comment by dmk1991** [comment]
Hey guys, this likely originally got merged in while one of us was testing the omniauth features from a while ago. If you look at the schema changes from that PR you'll see the same users and identities table being created to be used with the omniauth functionality. I think one of my PRs included those lines as well, not sure how it got back in though.

If you guys would like, I can drop my database and re-run the migrations to get a clean schema and push it up as a PR, that way were all running at the same place again.

**Comment by chuong** [comment]
This issue is now fixed in PR #33.

**Comment by dmk1991** [comment]
Awesome, lets just make sure we close out this issue once the PR gets merged. Thanks for getting it cleaned up @chuong.

**Comment by dmk1991** [comment]
PR was merged that solves this schema issue so I'm going to go ahead and close out this issue.
